services:
  i1s3:
    build:
      context: .
      dockerfile: i1s3.dockerfile
    image: i1s3-local:oraclelinux9

  i1:
    build:
      context: .
      dockerfile: i1.dockerfile
    container_name: i1
    hostname: i1
    networks:
      - hnet
    volumes:
      - ./df/i1:/df
    tty: true
    depends_on:
      - i1s3
      - s1
      - s2
      - s3
      - p1
      - g1
    # command: /root/setup-ssh.sh

  s1:
    build:
      context: .
      dockerfile: s.dockerfile
    container_name: s1
    hostname: s1
    networks:
      - hnet
    ports:
      - "2221:22"
      - "4040:4040"
      - "8080:8080"
      - "8081:8081"
      - "8088:8088"
      - "9870:9870"
      - "19888:19888"
    volumes:
      - ./df/s1:/df
    tty: true
    depends_on:
      - i1s3
  s2:
    build:
      context: .
      dockerfile: s.dockerfile
    container_name: s2
    hostname: s2
    networks:
      - hnet
    ports:
      - "2222:22"
      - "8082:8081"
    volumes:
      - ./df/s2:/df
    tty: true
    depends_on:
      - i1s3
  s3:
    build:
      context: .
      dockerfile: s.dockerfile
    container_name: s3
    hostname: s3
    networks:
      - hnet
    ports:
      - "2223:22"
      - "8083:8081"
    volumes:
      - ./df/s3:/df
    tty: true
    depends_on:
      - i1s3
  p1:
    image: prom/prometheus
    container_name: p1
    hostname: p1
    networks:
      - hnet
    ports:
      - "9090:9090"
    volumes:
      - ./df/p1/prometheus.yml:/etc/prometheus/prometheus.yml
    tty: true
  g1:
    image: grafana/grafana
    container_name: g1
    hostname: g1
    networks:
      - hnet
    ports:
      - "3000:3000"
    volumes:
      - ./df/g1/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./df/g1/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./df/g1/provisioning/alerting:/etc/grafana/provisioning/alerting
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_ALERTING_PROVISIONING_ENABLED=true
      - GF_ALERTING_PROVISIONING_PATH=/etc/grafana/provisioning/alerting
    tty: true
networks:
  hnet:
    external: true
