{
 "title": "FMS Performance Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "성능 모니터링", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "raw-data 배치당 처리 소요 시간",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_sparkstreaming_driver_spark_streaming_raw_data_stream_latency_Value",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "processed-data 배치당 처리 소요 시간",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_sparkstreaming_driver_spark_streaming_processed_data_stream_latency_Value",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "fail-data 배치당 처리 소요 시간",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_sparkstreaming_driver_spark_streaming_fail_data_stream_latency_Value",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "error-data 배치당 처리 소요 시간",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_sparkstreaming_driver_spark_streaming_error_data_stream_latency_Value",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "raw-data 분 당 처리 레코드 수",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(increase(metrics_sparkstreaming_driver_spark_streaming_raw_data_stream_states_rowsTotal_Value[30s])[1m:30s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "processed-data 분 당 처리 레코드 수",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(increase(metrics_sparkstreaming_driver_spark_streaming_processed_data_stream_states_rowsTotal_Value[30s])[1m:30s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "fail-data 분 당 처리 레코드 수",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(increase(metrics_sparkstreaming_driver_spark_streaming_fail_data_stream_states_rowsTotal_Value[30s])[1m:30s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "error-data 분 당 처리 레코드 수",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(increase(metrics_sparkstreaming_driver_spark_streaming_error_data_stream_states_rowsTotal_Value[30s])[1m:30s])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}