global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['0.0.0.0:9090']
  - job_name: 'spark'
    static_configs:
      - targets: ['s1:4040']
    metrics_path: '/metrics/prometheus'