global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['0.0.0.0:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['s1:9100','s2:9100','s3:9100']
  - job_name: 'spark'
    static_configs:
      - targets: ['s1:4040']
    metrics_path: '/metrics/prometheus'
  - job_name: 'fms'
    static_configs:
      - targets: ['s1:9990']
  - job_name: 'error'
    static_configs:
      - targets: ['s1:9991']
  - job_name: 'raw'
    static_configs:
      - targets: ['s1:9993']